apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploymentwithpvc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mypodforpvc
  template:
    metadata:
      labels:
        app: mypodforpvc
    spec:
      containers:
        - name: mynginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: mypvcvolume
      volumes:
        - name: mypvcvolume
          persistentVolumeClaim:
            claimName: mypvc

---

kind: Service
apiVersion: v1
metadata:
  name: mynodeportservice
spec:
  selector:
    app: mypodforpvc
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8080
      nodePort: 30001