apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploymentwithnfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypodfornfs
  template:
    metadata:
      labels:
        app: mypodfornfs
    spec:
      containers:
      - name: myweb
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mynfsvolume
      volumes:
      - name: mynfsvolume
        nfs:
          server: 193.55.163.51
          path: "/nfs/test"

---

kind: Service
apiVersion: v1
metadata:
  name: mynodeportservice
spec:
  selector:
    app: mypodfornfs
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8080
      nodePort: 30001
