kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv
  labels:
    owner: mickaelbaron
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 193.55.163.51
    path: "/nfs/test"
