apiVersion: v1
kind: Pod
metadata:
  name: mypodwithlabels
  labels:
    release: stable
    environment: production
    tier: frontend
    version: "1.21"
spec:
  containers:
  - name: mycontainer-1
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: mycontainer-2
    image: alpine:3.14
    command: ["watch", "wget", "-qO-", "localhost"]